version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.9.5
    hostname: rabbitmq
  celery:
    build: toil-docker
    environment:
      - TMPDIR=${PWD}/freva-workdir/toil-workdir
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
      - ${PWD}/freva-workdir:${PWD}/freva-workdir
    command: celery --broker=amqp://guest:guest@rabbitmq:5672// -A toil.server.celery_app worker --loglevel=INFO
    depends_on:
      - rabbitmq
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_USER: freva
      MYSQL_PASSWORD: T3st
      MYSQL_DATABASE: freva
      MYSQL_ROOT_PASSWORD: test_password_please_ignore
    ports:
      - "3306:3306"
    volumes:
      - ./.devcontainer/mysql:/docker-entrypoint-initdb.d
  wes-server:
    build: toil-docker
    volumes:
      - ${PWD}/freva-workdir:${PWD}/freva-workdir
    environment:
      - TOIL_WES_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    # TODO: toil server ignores --host if not run in debug even though the code would suggest it shouldn't
    command: toil server --host 0.0.0.0 --port 8001 --debug --work_dir ${PWD}/freva-workdir/toil
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
      - celery
