# Generated by Django 4.1.3 on 2022-11-14 15:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workflows.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("cwl_version", models.CharField(max_length=5)),
                ("created", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "data",
                    models.FileField(upload_to=workflows.models.user_workflow_path),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
