name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install poetry
          poetry install
      - name: Run mypy
        run: poetry run mypy .
      - name: Run isort
        run: poetry run isort --check .
      - name: Run black
        run: poetry run black --check .
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Start compose
        run: docker compose up -d
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run Tests
        run: poetry run python manage.py test --keepdb
      - name: Tear down docker compose
        run: docker compose down

